import { createAccessControl } from "better-auth/plugins/access";
import { defaultStatements, adminAc } from "better-auth/plugins/admin/access";

/**
 * make sure to use `as const` so typescript can infer the type correctly
 */
const statement = {
  ...defaultStatements,
  // Admin submodules
  admin_dashboard: [
    "create",
    "share",
    "update",
    "deactivate",
    "reactivate",
    "view",
  ],
  admin_artworks: [
    "create",
    "share",
    "update",
    "deactivate",
    "reactivate",
    "view",
  ],
  admin_categories: [
    "create",
    "share",
    "update",
    "deactivate",
    "reactivate",
    "view",
  ],
  admin_collections: [
    "create",
    "share",
    "update",
    "deactivate",
    "reactivate",
    "view",
  ],
  admin_sizes: [
    "create",
    "share",
    "update",
    "deactivate",
    "reactivate",
    "view",
  ],
  admin_sales: [
    "create",
    "share",
    "update",
    "deactivate",
    "reactivate",
    "view",
  ],
  admin_sales_orders: [
    "create",
    "share",
    "update",
    "deactivate",
    "reactivate",
    "view",
  ],
  admin_sales_forms_of_payment: [
    "create",
    "share",
    "update",
    "deactivate",
    "reactivate",
    "view",
  ],
  admin_sales_vouchers: [
    "create",
    "share",
    "update",
    "deactivate",
    "reactivate",
    "view",
  ],
  admin_users: [
    "create",
    "share",
    "update",
    "deactivate",
    "reactivate",
    "view",
  ],
  admin_users_artists: [
    "create",
    "share",
    "update",
    "deactivate",
    "reactivate",
    "view",
  ],
  admin_users_clients: [
    "create",
    "share",
    "update",
    "deactivate",
    "reactivate",
    "view",
  ],
  admin_settings: [
    "create",
    "share",
    "update",
    "deactivate",
    "reactivate",
    "view",
  ],
  admin_notifications: [
    "create",
    "share",
    "update",
    "deactivate",
    "reactivate",
    "view",
  ],

  // Home routes
  home_index: ["view"],
  home_artworks: ["view"],
  home_artists: ["view"],
  home_contact: ["view"],
} as const;

export const ac = createAccessControl(statement);

export const admin = ac.newRole({
  ...adminAc.statements,
  admin_dashboard: [
    "create",
    "share",
    "update",
    "deactivate",
    "reactivate",
    "view",
  ],
  admin_artworks: [
    "create",
    "share",
    "update",
    "deactivate",
    "reactivate",
    "view",
  ],
  admin_categories: [
    "create",
    "share",
    "update",
    "deactivate",
    "reactivate",
    "view",
  ],
  admin_collections: [
    "create",
    "share",
    "update",
    "deactivate",
    "reactivate",
    "view",
  ],
  admin_sizes: [
    "create",
    "share",
    "update",
    "deactivate",
    "reactivate",
    "view",
  ],
  admin_sales: [
    "create",
    "share",
    "update",
    "deactivate",
    "reactivate",
    "view",
  ],
  admin_sales_orders: [
    "create",
    "share",
    "update",
    "deactivate",
    "reactivate",
    "view",
  ],
  admin_sales_forms_of_payment: [
    "create",
    "share",
    "update",
    "deactivate",
    "reactivate",
    "view",
  ],
  admin_sales_vouchers: [
    "create",
    "share",
    "update",
    "deactivate",
    "reactivate",
    "view",
  ],
  admin_users: [
    "create",
    "share",
    "update",
    "deactivate",
    "reactivate",
    "view",
  ],
  admin_users_artists: [
    "create",
    "share",
    "update",
    "deactivate",
    "reactivate",
    "view",
  ],
  admin_users_clients: [
    "create",
    "share",
    "update",
    "deactivate",
    "reactivate",
    "view",
  ],
  admin_settings: [
    "create",
    "share",
    "update",
    "deactivate",
    "reactivate",
    "view",
  ],
  admin_notifications: [
    "create",
    "share",
    "update",
    "deactivate",
    "reactivate",
    "view",
  ],
  home_index: ["view"],
  home_artworks: ["view"],
  home_artists: ["view"],
  home_contact: ["view"],
});

export const artist = ac.newRole({
  admin_dashboard: ["view"],
  admin_artworks: ["create", "update", "deactivate", "reactivate", "view"],
  admin_categories: ["view"],
  admin_collections: ["view"],
  admin_sizes: ["view"],
  admin_sales: ["view"],
  admin_sales_orders: ["view"],
  admin_sales_forms_of_payment: ["view"],
  admin_sales_vouchers: ["view"],
  admin_users: ["view"],
  admin_users_artists: ["view"],
  admin_users_clients: ["view"],
  admin_settings: ["view"],
  admin_notifications: ["view"],
  home_index: ["view"],
  home_artworks: ["view"],
  home_artists: ["view"],
  home_contact: ["view"],
});

export const client = ac.newRole({
  home_index: ["view"],
  home_artworks: ["view"],
  home_artists: ["view"],
  home_contact: ["view"],
});
